// Package banner plays usher's animated startup banner: plain-text frames
// plus a semantic color layer, colorized at render time with 4-bit ANSI.
// Frames are generated by assets/banner/frames.py (the source of truth)
// and embedded here. Engineering approach follows GitHub Copilot CLI's
// banner write-up.
package banner

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"
	"time"
)

//go:embed frames.json
var framesJSON []byte

type frame struct {
	Title    string            `json:"title"`
	Duration int               `json:"duration"` // ms
	Content  string            `json:"content"`
	Colors   map[string]string `json:"colors"` // "row,col" -> role
}

type animation struct {
	Width  int     `json:"width"`
	Height int     `json:"height"`
	Frames []frame `json:"frames"`
}

// Semantic role -> 4-bit SGR foreground code. Theme-friendly by design.
var ansi = map[string]int{
	"letter_dim": 90, "letter_lit": 37, "letter_hot": 93, "letter_white": 97,
	"suit": 97, "eyes": 30, "bowtie": 91,
	"beam": 93, "sparkle": 93, "tagline": 90,
}

// ShouldAnimate applies every gate from the spec.
func ShouldAnimate(noBannerFlag bool) bool {
	if noBannerFlag {
		return false
	}
	if os.Getenv("NO_COLOR") != "" || os.Getenv("USHER_NO_BANNER") != "" {
		return false
	}
	fi, err := os.Stdout.Stat()
	if err != nil || fi.Mode()&os.ModeCharDevice == 0 {
		return false
	}
	return true
}

// renderLine colorizes one row, batching consecutive same-role cells into a
// single SGR run to minimize escape-code overhead. With color=false it emits
// no escape sequences at all (NO_COLOR compliance, per no-color.org).
func renderLine(line string, roles map[int]string, color bool) string {
	if !color {
		return line
	}
	var sb strings.Builder
	current := -2 // sentinel: no SGR emitted yet
	for i, ch := range []rune(line) {
		code := current // spaces keep current color
		if ch != ' ' {
			code = -1 // default to reset for non-spaces without role
			if role, ok := roles[i]; ok {
				if c, ok := ansi[role]; ok {
					code = c
				}
			}
		}
		if code != current {
			if code == -1 {
				sb.WriteString("\x1b[0m")
			} else {
				fmt.Fprintf(&sb, "\x1b[%dm", code)
			}
			current = code
		}
		sb.WriteRune(ch)
	}
	sb.WriteString("\x1b[0m")
	return sb.String()
}

func renderFrame(f frame, color bool) string {
	lines := strings.Split(f.Content, "\n")
	out := make([]string, len(lines))
	for r, line := range lines {
		roles := map[int]string{}
		for key, role := range f.Colors {
			var rr, cc int
			fmt.Sscanf(key, "%d,%d", &rr, &cc)
			if rr == r {
				roles[cc] = role
			}
		}
		out[r] = renderLine(line, roles, color)
	}
	return strings.Join(out, "\n")
}

// Play writes the banner to w. With animate=false it prints only the final
// frame — no motion, no cursor tricks (safe for pipes and screen readers).
// Per no-color.org, any non-empty NO_COLOR suppresses all SGR escapes, in
// both the static and animated paths.
func Play(w io.Writer, animate bool) error {
	var anim animation
	if err := json.Unmarshal(framesJSON, &anim); err != nil {
		return err
	}
	if len(anim.Frames) == 0 {
		return fmt.Errorf("banner: no frames")
	}
	color := os.Getenv("NO_COLOR") == ""
	if !animate {
		_, err := fmt.Fprintln(w, renderFrame(anim.Frames[len(anim.Frames)-1], color))
		return err
	}
	fmt.Fprint(w, "\x1b[?25l")
	defer fmt.Fprint(w, "\x1b[?25h")
	for i, f := range anim.Frames {
		if i > 0 {
			fmt.Fprintf(w, "\x1b[%dA", anim.Height)
		}
		fmt.Fprintln(w, renderFrame(f, color))
		time.Sleep(time.Duration(f.Duration) * time.Millisecond)
	}
	return nil
}
